// =========================================================================
// 🎟️ OFFICIAL PAID TICKET DIRECTORY (48 PARTICIPANTS)
// IESA Process Day 2026 — Verified Paid Delegates Roster
// =========================================================================

export interface PaidParticipantItem {
  id: string;
  orderNumber: number;
  ticketName: string;
  fullName: string;
  matricNumber: string;
  department: string;
  email: string;
  phone?: string;
}

export const OFFICIAL_PAID_DIRECTORY: PaidParticipantItem[] = [
  {
    id: "paid-01",
    orderNumber: 1,
    ticketName: "Abdulkabir Umoru",
    fullName: "Abdulkabir Umoru",
    matricNumber: "244079",
    department: "Industrial & Production Engineering",
    email: "umoruabdulkabir@gmail.com",
    phone: "",
  },
  {
    id: "paid-02",
    orderNumber: 2,
    ticketName: "Abisola Lasisi",
    fullName: "Abisola Lasisi",
    matricNumber: "251141",
    department: "Industrial & Production Engineering",
    email: "olawaosepinabisola05@gmail.com",
    phone: "08088932966",
  },
  {
    id: "paid-03",
    orderNumber: 3,
    ticketName: "Adeayo Aderinkomi",
    fullName: "Adeayo Aderinkomi",
    matricNumber: "259088",
    department: "Industrial & Production Engineering",
    email: "adeayoaderinkomi@gmail.com",
    phone: "08116215676",
  },
  {
    id: "paid-04",
    orderNumber: 4,
    ticketName: "Adeyemi Aderomola",
    fullName: "Adeyemi Aderomola",
    matricNumber: "ADEYEMI-ADEROMOLA",
    department: "Industrial & Production Engineering (External)",
    email: "kehinde.adeyemi976@gmail.com",
    phone: "09163343959",
  },
  {
    id: "paid-05",
    orderNumber: 5,
    ticketName: "Alade Taiwo",
    fullName: "Alade Taiwo",
    matricNumber: "231537",
    department: "Industrial & Production Engineering",
    email: "aladetaiwo19@gmail.com",
    phone: "08029892079",
  },
  {
    id: "paid-06",
    orderNumber: 6,
    ticketName: "Ayomide Adebisi",
    fullName: "Ayomide Adebisi",
    matricNumber: "251708",
    department: "Industrial & Production Engineering",
    email: "aadebisi251708@stu.ui.edu.ng",
    phone: "",
  },
  {
    id: "paid-07",
    orderNumber: 7,
    ticketName: "Bolarinwa Ayorinde",
    fullName: "Bolarinwa Ayorinde",
    matricNumber: "BOLARINWA-AYORINDE",
    department: "Systems Engineering",
    email: "bolarinwaayorinde97@gmail.com",
    phone: "09068938558",
  },
  {
    id: "paid-08",
    orderNumber: 8,
    ticketName: "Boluwatife Oladimeji",
    fullName: "Boluwatife Oladimeji",
    matricNumber: "236883",
    department: "Industrial & Production Engineering",
    email: "boluoladimeji366@gmail.com",
    phone: "",
  },
  {
    id: "paid-09",
    orderNumber: 9,
    ticketName: "Charles Adebiyi",
    fullName: "Charles Adebiyi",
    matricNumber: "258410",
    department: "Industrial & Production Engineering",
    email: "charlesadebiyi15@gmail.com",
    phone: "",
  },
  {
    id: "paid-10",
    orderNumber: 10,
    ticketName: "Chikezie Chukwuebuka",
    fullName: "Chikezie Chukwuebuka",
    matricNumber: "231543",
    department: "Industrial & Production Engineering",
    email: "chukwuebukachikezie409@gmail.com",
    phone: "09132301534",
  },
  {
    id: "paid-11",
    orderNumber: 11,
    ticketName: "Chimeremuma Ugochukwu",
    fullName: "Chimeremuma Ugochukwu",
    matricNumber: "258452",
    department: "Faculty of Technology",
    email: "ugochukwudavid321@gmail.com",
    phone: "09034105688",
  },
  {
    id: "paid-12",
    orderNumber: 12,
    ticketName: "Chukwuemeka Offor",
    fullName: "Chukwuemeka Offor",
    matricNumber: "236880",
    department: "Industrial & Production Engineering",
    email: "emekaofforleon@gmail.com",
    phone: "",
  },
  {
    id: "paid-13",
    orderNumber: 13,
    ticketName: "Dalmeida Roseline",
    fullName: "Dalmeida Roseline Sesi",
    matricNumber: "258424",
    department: "Industrial & Production Engineering",
    email: "dalmeidaroseline16@gmail.com",
    phone: "",
  },
  {
    id: "paid-14",
    orderNumber: 14,
    ticketName: "DivineFavour Douglas",
    fullName: "DivineFavour Douglas",
    matricNumber: "244041",
    department: "Industrial & Production Engineering",
    email: "divinedouglas74@gmail.com",
    phone: "",
  },
  {
    id: "paid-15",
    orderNumber: 15,
    ticketName: "Echu Wisdom",
    fullName: "Echu Wisdom",
    matricNumber: "ECHU-WISDOM",
    department: "Petroleum Engineering",
    email: "echuwisdom4@gmail.com",
    phone: "09134387706",
  },
  {
    id: "paid-16",
    orderNumber: 16,
    ticketName: "Faithful Olinmah",
    fullName: "Faithful Olinmah",
    matricNumber: "231561",
    department: "Industrial & Production Engineering",
    email: "olinmahfaithful57@gmail.com",
    phone: "",
  },
  {
    id: "paid-17",
    orderNumber: 17,
    ticketName: "Favour Ikpea",
    fullName: "Favour Ikpea",
    matricNumber: "244052",
    department: "Industrial & Production Engineering",
    email: "ikpeafavour6@gmail.com",
    phone: "",
  },
  {
    id: "paid-18",
    orderNumber: 18,
    ticketName: "Fredrick Adelaja",
    fullName: "Fredrick Adelaja",
    matricNumber: "231525",
    department: "Industrial & Production Engineering",
    email: "fredrickadelaja@gmail.com",
    phone: "",
  },
  {
    id: "paid-19",
    orderNumber: 19,
    ticketName: "Ihemelandu Kingsley",
    fullName: "Ihemelandu Kingsley",
    matricNumber: "IHEMELANDU-KINGSLEY",
    department: "Systems Engineering",
    email: "kingsleydaprime@gmail.com",
    phone: "09035810428",
  },
  {
    id: "paid-20",
    orderNumber: 20,
    ticketName: "Iyeoluwa Obabiyi",
    fullName: "Iyeoluwa Johnson Obabiyi",
    matricNumber: "258435",
    department: "Industrial & Production Engineering",
    email: "iobabiyi258435@stu.ui.edu.ng",
    phone: "",
  },
  {
    id: "paid-21",
    orderNumber: 21,
    ticketName: "Jesutofunmi Soyibo",
    fullName: "Jesutofunmi Soyibo",
    matricNumber: "231574",
    department: "Industrial & Production Engineering",
    email: "jesutofunmisoyibo24@gmail.com",
    phone: "09124837346",
  },
  {
    id: "paid-22",
    orderNumber: 22,
    ticketName: "Joseph Okerentugba",
    fullName: "Joseph Okerentugba",
    matricNumber: "231558",
    department: "Industrial & Production Engineering",
    email: "jokerentugba558@stu.ui.edu.ng",
    phone: "",
  },
  {
    id: "paid-23",
    orderNumber: 23,
    ticketName: "Joshua Afia",
    fullName: "Joshua Afia",
    matricNumber: "231530",
    department: "Industrial & Production Engineering",
    email: "afiajoshua85@gmail.com",
    phone: "",
  },
  {
    id: "paid-24",
    orderNumber: 24,
    ticketName: "Kuforiji Hikmat",
    fullName: "Kuforiji Hikmat",
    matricNumber: "231552",
    department: "Industrial & Production Engineering",
    email: "hikmatkuforiji@gmail.com",
    phone: "08080558809",
  },
  {
    id: "paid-25",
    orderNumber: 25,
    ticketName: "Maemunah Jibril",
    fullName: "Maemunah Jibril",
    matricNumber: "231550",
    department: "Industrial & Production Engineering",
    email: "maemunahjibril@gmail.com",
    phone: "",
  },
  {
    id: "paid-26",
    orderNumber: 26,
    ticketName: "Mark Enoch",
    fullName: "Mark Enoch",
    matricNumber: "258433",
    department: "Industrial & Production Engineering",
    email: "enomark191@gmail.com",
    phone: "",
  },
  {
    id: "paid-27",
    orderNumber: 27,
    ticketName: "Mary Akinsanmi",
    fullName: "Mary Akinsanmi",
    matricNumber: "258420",
    department: "Industrial & Production Engineering",
    email: "maryakinsanmi2@gmail.com",
    phone: "",
  },
  {
    id: "paid-28",
    orderNumber: 28,
    ticketName: "Mary Oyeyimika",
    fullName: "Mary Oyeyimika",
    matricNumber: "236892",
    department: "Industrial & Production Engineering",
    email: "moyeyimika22@gmail.com",
    phone: "09075703751",
  },
  {
    id: "paid-29",
    orderNumber: 29,
    ticketName: "Mubarak Ahmed",
    fullName: "Mubarak Ahmed",
    matricNumber: "251114",
    department: "Faculty of Technology",
    email: "ahmedlatifat100@gmail.com",
    phone: "08059438210",
  },
  {
    id: "paid-30",
    orderNumber: 30,
    ticketName: "Mutmaina Adedokun",
    fullName: "Mutmaina Adedokun",
    matricNumber: "251107",
    department: "Industrial & Production Engineering",
    email: "adedokunmutmaina@gmail.com",
    phone: "09068897350",
  },
  {
    id: "paid-31",
    orderNumber: 31,
    ticketName: "Nsikakabasi Ukoh",
    fullName: "Nsikakabasi Ukoh",
    matricNumber: "231579",
    department: "Industrial & Production Engineering",
    email: "ukohnsikakabasiunex@gmail.com",
    phone: "",
  },
  {
    id: "paid-32",
    orderNumber: 32,
    ticketName: "Nwabunka Anthony",
    fullName: "Nwabunka Anthony",
    matricNumber: "244061",
    department: "Industrial & Production Engineering",
    email: "nwabunkaa@gmail.com",
    phone: "",
  },
  {
    id: "paid-33",
    orderNumber: 33,
    ticketName: "Obaloluwa Olayinka",
    fullName: "Obaloluwa Olayinka",
    matricNumber: "251154",
    department: "Industrial & Production Engineering",
    email: "olayinkaobaloluwa04@gmail.com",
    phone: "",
  },
  {
    id: "paid-34",
    orderNumber: 34,
    ticketName: "Ogundipe David",
    fullName: "Ogundipe David",
    matricNumber: "231557",
    department: "Industrial & Production Engineering",
    email: "ogundipeoluwayomi@gmail.com",
    phone: "",
  },
  {
    id: "paid-35",
    orderNumber: 35,
    ticketName: "Okhaioisevai Adeoye",
    fullName: "Okhaioisevai Adeoye",
    matricNumber: "231526",
    department: "Industrial & Production Engineering",
    email: "okhaioisevai44@gmail.com",
    phone: "",
  },
  {
    id: "paid-36",
    orderNumber: 36,
    ticketName: "Olayinka Ayantosho",
    fullName: "Olayinka Ayantosho",
    matricNumber: "231541",
    department: "Industrial & Production Engineering",
    email: "oayantosho541@stu.ui.edu.ng",
    phone: "",
  },
  {
    id: "paid-37",
    orderNumber: 37,
    ticketName: "Oluwateniara Alli",
    fullName: "Oluwateniara Alli",
    matricNumber: "258422",
    department: "Industrial & Production Engineering",
    email: "oalli258422@stu.ui.edu.ng",
    phone: "",
  },
  {
    id: "paid-38",
    orderNumber: 38,
    ticketName: "Omoemi Israel",
    fullName: "Omoemi Israel",
    matricNumber: "244074",
    department: "Industrial & Production Engineering",
    email: "omoemiisrael@gmail.com",
    phone: "",
  },
  {
    id: "paid-39",
    orderNumber: 39,
    ticketName: "Peace Ojo",
    fullName: "Peace Ojo",
    matricNumber: "258436",
    department: "Industrial & Production Engineering",
    email: "pojo258436@stu.ui.edu.ng",
    phone: "",
  },
  {
    id: "paid-40",
    orderNumber: 40,
    ticketName: "Precious Adetipe",
    fullName: "Precious Adetipe",
    matricNumber: "231527",
    department: "Industrial & Production Engineering",
    email: "padetipe527@stu.ui.edu.ng",
    phone: "",
  },
  {
    id: "paid-41",
    orderNumber: 41,
    ticketName: "Precious Ajao",
    fullName: "Precious Ajao",
    matricNumber: "231531",
    department: "Industrial & Production Engineering",
    email: "ajaoprecious11@gmail.com",
    phone: "",
  },
  {
    id: "paid-42",
    orderNumber: 42,
    ticketName: "Rhema Victor-Menekpo",
    fullName: "Rhema Victor-Menekpo",
    matricNumber: "244080",
    department: "Industrial & Production Engineering",
    email: "menekporhema@gmail.com",
    phone: "",
  },
  {
    id: "paid-43",
    orderNumber: 43,
    ticketName: "Samuel Ogunbambi",
    fullName: "Samuel Promise Ogunbambi",
    matricNumber: "231555",
    department: "Industrial & Production Engineering",
    email: "ogunbambis6@gmail.com",
    phone: "08038963790",
  },
  {
    id: "paid-44",
    orderNumber: 44,
    ticketName: "Samuel Toriola",
    fullName: "Samuel oluwafemi Toriola",
    matricNumber: "258451",
    department: "Industrial & Production Engineering",
    email: "samuelttoriola97@gmail.com",
    phone: "",
  },
  {
    id: "paid-45",
    orderNumber: 45,
    ticketName: "Somtochukwu Onwe",
    fullName: "Somtochukwu Onwe",
    matricNumber: "231570",
    department: "Industrial & Production Engineering",
    email: "somtobilo@gmail.com",
    phone: "",
  },
  {
    id: "paid-46",
    orderNumber: 46,
    ticketName: "Sotunde Ireoluwa",
    fullName: "Sotunde Ireoluwa",
    matricNumber: "250867",
    department: "Agricultural Engineering",
    email: "iresotunde@gmail.com",
    phone: "08086238918",
  },
  {
    id: "paid-47",
    orderNumber: 47,
    ticketName: "Victoria Olawunmi",
    fullName: "Victoria Olawunmi",
    matricNumber: "258439",
    department: "Industrial & Production Engineering",
    email: "volawunmi258439@stu.ui.edu.ng",
    phone: "",
  },
  {
    id: "paid-48",
    orderNumber: 48,
    ticketName: "Zainab Amiola",
    fullName: "Zainab Amiola",
    matricNumber: "237566",
    department: "Industrial & Production Engineering",
    email: "zamiola566@stu.ui.edu.ng",
    phone: "",
  },
];

// Helper to look up an attendee in the official paid directory
export function findPaidParticipant(query: string): PaidParticipantItem | null {
  if (!query) return null;
  const clean = query.trim().toLowerCase();

  return (
    OFFICIAL_PAID_DIRECTORY.find((p) => {
      if (p.matricNumber.toLowerCase() === clean) return true;
      if (p.email.toLowerCase() === clean) return true;
      if (p.fullName.toLowerCase() === clean) return true;
      if (p.ticketName.toLowerCase() === clean) return true;
      if (p.id.toLowerCase() === clean) return true;
      // Partial name match if query is longer than 3 chars
      if (clean.length >= 4 && (p.fullName.toLowerCase().includes(clean) || p.ticketName.toLowerCase().includes(clean))) {
        return true;
      }
      return false;
    }) || null
  );
}
