export interface ProgramSessionItem {
  id: string;
  orderNumber: number;
  title: string;
  shortTitle: string;
  speaker?: string;
  category: string;
  duration: string;
  location: string;
}

export const OFFICIAL_PROGRAM_SESSIONS: ProgramSessionItem[] = [
  {
    id: "session-01",
    orderNumber: 1,
    title: "Arrival, Anthems, Interactive Welcome & Presidential Speech",
    shortTitle: "Arrival & Welcome",
    speaker: "IESA President & Executive Council",
    category: "Protocols & Ceremonies",
    duration: "35 mins",
    location: "KAAF Main Auditorium",
  },
  {
    id: "session-02",
    orderNumber: 2,
    title: "1st Keynote Session: VC Opening Address & Q&A",
    shortTitle: "VC Opening Keynote",
    speaker: "Prof. Kayode Oyebode Adebowale (VC, UI)",
    category: "Keynotes & Talks",
    duration: "30 mins",
    location: "KAAF Main Auditorium",
  },
  {
    id: "session-03",
    orderNumber: 3,
    title: "Headline Sponsor Address & Strategic Spotlight",
    shortTitle: "Headline Sponsor Address",
    speaker: "Headline Sponsor Leadership Team",
    category: "Keynotes & Talks",
    duration: "10 mins",
    location: "KAAF Main Stage",
  },
  {
    id: "session-04",
    orderNumber: 4,
    title: "2nd Speaker Session: AI, Robotics & Process Discipline",
    shortTitle: "Dr. Ayoola Keynote",
    speaker: "Dr. Olusola Sayeed Ayoola (RAIN)",
    category: "Keynotes & Talks",
    duration: "30 mins",
    location: "KAAF Main Auditorium",
  },
  {
    id: "session-05",
    orderNumber: 5,
    title: "Delegate Giveaway & Engagement Interlude",
    shortTitle: "Delegate Giveaway",
    speaker: "Conference Welfare & Engagement Leads",
    category: "Protocols & Ceremonies",
    duration: "5 mins",
    location: "KAAF Main Stage",
  },
  {
    id: "session-06",
    orderNumber: 6,
    title: "Annual Student Debate & Intellectual Discourse",
    shortTitle: "Annual Student Debate",
    speaker: "Invited University Student Debaters",
    category: "Competitions",
    duration: "30 mins",
    location: "KAAF Main Stage",
  },
  {
    id: "session-07",
    orderNumber: 7,
    title: "3rd Speaker Session: Executive Career & Capacity",
    shortTitle: "Engr. Otokiti Keynote",
    speaker: "Engr. Adebayo Otokiti (Calor Gas UK)",
    category: "Keynotes & Talks",
    duration: "30 mins",
    location: "KAAF Main Auditorium",
  },
  {
    id: "session-08",
    orderNumber: 8,
    title: "Keynote Speaker Honors & Networking Break",
    shortTitle: "Speaker Honors & Break",
    speaker: "Staff Adviser & Conference Convener",
    category: "Protocols & Ceremonies",
    duration: "10 mins",
    location: "Executive Lounge & Hall",
  },
  {
    id: "session-09",
    orderNumber: 9,
    title: "Simultaneous Masterclasses: Energy, Robotics, Cybersecurity & Tech Law",
    shortTitle: "Technical Workshops",
    speaker: "Itel Energy, Cyvant, Aurora Robotics & IP Uncomplicated",
    category: "Workshops",
    duration: "30 mins",
    location: "Department Engineering Labs",
  },
  {
    id: "session-10",
    orderNumber: 10,
    title: "Chairman Keynote Address: Industrial Horizons",
    shortTitle: "Chairman Keynote",
    speaker: "Conference Chairman & Distinguished Alumnus",
    category: "Keynotes & Talks",
    duration: "15 mins",
    location: "KAAF Main Auditorium",
  },
  {
    id: "session-11",
    orderNumber: 11,
    title: "IEPOD Hackathon Live Project Pitches & Grand Finals",
    shortTitle: "Hackathon Finals",
    speaker: "Finalist Student Builder Teams",
    category: "Competitions",
    duration: "45 mins",
    location: "KAAF Main Stage",
  },
  {
    id: "session-12",
    orderNumber: 12,
    title: "Interactive Engagement, Mini Games & Audience Prizes",
    shortTitle: "Audience Games & Prizes",
    speaker: "Student Engagement Directors",
    category: "Protocols & Ceremonies",
    duration: "15 mins",
    location: "KAAF Main Auditorium",
  },
  {
    id: "session-13",
    orderNumber: 13,
    title: "Research Paper Presentations & Academic Oral Defenses",
    shortTitle: "Research Paper Defenses",
    speaker: "Selected Student Authors & Faculty Judges",
    category: "Paper Presentations",
    duration: "55 mins",
    location: "Academic Stage",
  },
  {
    id: "session-14",
    orderNumber: 14,
    title: "Hackathon Winners, Merit Awards, Vote of Thanks & Protocols",
    shortTitle: "Awards & Closing",
    speaker: "IESA Executives & Conference Planning Committee",
    category: "Protocols & Ceremonies",
    duration: "15 mins",
    location: "KAAF Main Stage",
  },
];
