export type ScheduleCategory =
  | "Keynotes & Talks"
  | "Workshops"
  | "Competitions"
  | "Paper Presentations"
  | "Protocols & Ceremonies";

export interface ProgramSessionItem {
  id: string;
  orderNumber: number;
  order: string;
  time: string;
  duration: string;
  title: string;
  shortTitle: string;
  speaker?: string;
  category: ScheduleCategory;
  description: string;
  location: string;
  imageUrl: string;
  photoCaption?: string;
  stampText?: string;
  badgeColor?: string;
}

export const OFFICIAL_PROGRAM_SESSIONS: ProgramSessionItem[] = [
  {
    id: "session-01",
    orderNumber: 1,
    order: "Session 01",
    time: "10:00 - 10:05 AM",
    duration: "5 mins",
    title: "Welcome - Guest and Attendees Arrival",
    shortTitle: "Arrival & Reception",
    speaker: "Protocol Officers & Ushers",
    category: "Protocols & Ceremonies",
    description: "Arrival, accreditation, and warm welcome of distinguished guests, faculty members, and student delegates.",
    location: "KAAF Main Entrance & Foyer",
    imageUrl: "/assets/generated/logo.png",
    photoCaption: "Welcome & Attendee Arrival at KAAF Foyer",
    stampText: "SESSION // 01 · WELCOME",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-02",
    orderNumber: 2,
    order: "Session 02",
    time: "10:05 - 10:10 AM",
    duration: "5 mins",
    title: "Host Test and Introduction",
    shortTitle: "Host Introduction",
    speaker: "Master of Ceremony (MC)",
    category: "Protocols & Ceremonies",
    description: "Host audio test, opening announcements, ground rules, and official introduction of the conference theme.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/iso_ticket_badge.png",
    photoCaption: "Host Stage Introduction & Conference Overview",
    stampText: "SESSION // 02 · INTRO",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-03",
    orderNumber: 3,
    order: "Session 03",
    time: "10:10 - 10:12 AM",
    duration: "2 mins",
    title: "Opening Prayer",
    shortTitle: "Opening Prayer",
    speaker: "Appointed Delegate",
    category: "Protocols & Ceremonies",
    description: "Solemn opening prayer invoking guidance, wisdom, and successful proceedings for the conference day.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/kaaf_keynote.png",
    photoCaption: "Opening Prayer with Assembled Delegates",
    stampText: "SESSION // 03 · PRAYER",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-04",
    orderNumber: 4,
    order: "Session 04",
    time: "10:12 - 10:20 AM",
    duration: "8 mins",
    title: "National Anthem & School Anthem",
    shortTitle: "Anthems",
    speaker: "Assembly of Delegates",
    category: "Protocols & Ceremonies",
    description: "Standing rendition of the Nigerian National Anthem and the University of Ibadan Anthem.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/logo.png",
    photoCaption: "Standing Rendition of National & UI Anthems",
    stampText: "SESSION // 04 · ANTHEMS",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-05",
    orderNumber: 5,
    order: "Session 05",
    time: "10:20 - 10:30 AM",
    duration: "10 mins",
    title: "Short Attendee Interactive Session",
    shortTitle: "Interactive Session",
    speaker: "Host & Student Engagement Leads",
    category: "Protocols & Ceremonies",
    description: "High-energy icebreaker, audience pulse-check, networking roll call, and interactive expectations setting.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/iso_gear_ai.png",
    photoCaption: "Audience Pulse-Check & Interactive Icebreaker",
    stampText: "SESSION // 05 · ICEBREAKER",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-06",
    orderNumber: 6,
    order: "Session 06",
    time: "10:30 - 10:35 AM",
    duration: "5 mins",
    title: "President Speech & HOD Opening Address",
    shortTitle: "President & HOD Speech",
    speaker: "IESA President & Head of Department",
    category: "Protocols & Ceremonies",
    description: "Welcome addresses by the IESA President and the Head of Department, Industrial and Production Engineering.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/logo.png",
    photoCaption: "IESA President & Department Leadership Welcome Address",
    stampText: "SESSION // 06 · SPEECHES",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-07",
    orderNumber: 7,
    order: "Session 07",
    time: "10:35 - 11:00 AM",
    duration: "25 mins",
    title: "1st Speaker Session: VC Opening Keynote",
    shortTitle: "VC Keynote (1st Speaker)",
    speaker: "Prof. Kayode Oyebode Adebowale (VC, University of Ibadan)",
    category: "Keynotes & Talks",
    description: "Flagship Keynote Address exploring institutional excellence, research commercialization, and industrial transformation.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/vice_chancellor.png",
    photoCaption: "Prof. Kayode Oyebode Adebowale · Vice-Chancellor, University of Ibadan",
    stampText: "SESSION // 07 · VC KEYNOTE",
    badgeColor: "bg-[#c6f552] text-[#040032]",
  },
  {
    id: "session-08",
    orderNumber: 8,
    order: "Session 08",
    time: "11:00 - 11:05 AM",
    duration: "5 mins",
    title: "Q and A: VC Keynote Session",
    shortTitle: "VC Keynote Q&A",
    speaker: "Prof. Kayode Oyebode Adebowale & Delegates",
    category: "Keynotes & Talks",
    description: "Direct interactive Q&A session where delegates pose questions to the Vice-Chancellor.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/vice_chancellor.png",
    photoCaption: "Interactive Q&A with the Vice-Chancellor",
    stampText: "SESSION // 08 · VC Q&A",
    badgeColor: "bg-[#c6f552] text-[#040032]",
  },
  {
    id: "session-09",
    orderNumber: 9,
    order: "Session 09",
    time: "11:05 - 11:15 AM",
    duration: "10 mins",
    title: "Sponsor Talk: Headline Sponsor Spotlight",
    shortTitle: "Headline Sponsor Talk",
    speaker: "Headline Sponsor Leadership Team",
    category: "Keynotes & Talks",
    description: "Strategic address by the Headline Sponsor highlighting industrial partnerships, student career avenues, and technology support.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/iso_ticket_badge.png",
    photoCaption: "Headline Sponsor Strategic Spotlight & Opportunities",
    stampText: "SESSION // 09 · SPONSOR",
    badgeColor: "bg-[#c6f552] text-[#040032]",
  },
  {
    id: "session-10",
    orderNumber: 10,
    order: "Session 10",
    time: "11:15 - 11:40 AM",
    duration: "25 mins",
    title: "2nd Speaker Session: Dr. Olusola Ayoola (RAIN)",
    shortTitle: "Dr. Ayoola Keynote (2nd Speaker)",
    speaker: "Dr. Olusola Sayeed Ayoola (Founder & CEO, RAIN)",
    category: "Keynotes & Talks",
    description: "Keynote Address: 'Building What AI Can't Replace: How Process Discipline Creates Impact, Not Just Output'.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/ayoola.png",
    photoCaption: "Dr. Olusola Sayeed Ayoola · Founder & CEO, Robotics and Artificial Intelligence Nigeria",
    stampText: "SESSION // 10 · RAIN AI",
    badgeColor: "bg-[#c6f552] text-[#040032]",
  },
  {
    id: "session-11",
    orderNumber: 11,
    order: "Session 11",
    time: "11:40 - 11:45 AM",
    duration: "5 mins",
    title: "Q and A: Dr. Olusola Ayoola",
    shortTitle: "Dr. Ayoola Q&A",
    speaker: "Dr. Olusola Sayeed Ayoola & Delegates",
    category: "Keynotes & Talks",
    description: "Audience questions on robotics applications, autonomous systems engineering, and practical technical careers.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/ayoola.png",
    photoCaption: "Audience Q&A on Robotics and Process Discipline",
    stampText: "SESSION // 11 · RAIN Q&A",
    badgeColor: "bg-[#c6f552] text-[#040032]",
  },
  {
    id: "session-12",
    orderNumber: 12,
    order: "Session 12",
    time: "11:45 - 11:50 AM",
    duration: "5 mins",
    title: "Giveaway Session (Optional)",
    shortTitle: "Giveaway Session",
    speaker: "Conference Welfare & Engagement Leads",
    category: "Protocols & Ceremonies",
    description: "Interactive delegate prize giveaways, conference merchandise drops, and trivia rewards for active participants.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/iso_ticket_badge.png",
    photoCaption: "Merchandise Giveaway & Delegate Prize Distribution",
    stampText: "SESSION // 12 · GIVEAWAY",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-13",
    orderNumber: 13,
    order: "Session 13",
    time: "11:50 AM - 12:10 PM",
    duration: "20 mins",
    title: "Annual Student Debate",
    shortTitle: "Student Debate",
    speaker: "Student Debate Finalists & Moderator",
    category: "Competitions",
    description: "High-octane academic debate exploring contemporary industrial engineering challenges, emerging automation, and human systems.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/iso_gear_ai.png",
    photoCaption: "Annual Undergraduate Debate Championship",
    stampText: "SESSION // 13 · DEBATE",
    badgeColor: "bg-[#ffdb58] text-[#040032]",
  },
  {
    id: "session-14",
    orderNumber: 14,
    order: "Session 14",
    time: "12:10 - 12:15 PM",
    duration: "5 mins",
    title: "Study Path / Scholarship Spotlight",
    shortTitle: "Study / Scholarship Spotlight",
    speaker: "Academic Panelist / Sponsor",
    category: "Keynotes & Talks",
    description: "Informative feature on scholarship pathways, postgraduate study opportunities, and academic excellence grants.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/iso_analytics_card.png",
    photoCaption: "Scholarship & Postgraduate Study Pathways Feature",
    stampText: "SESSION // 14 · SCHOLARSHIPS",
    badgeColor: "bg-[#c6f552] text-[#040032]",
  },
  {
    id: "session-15",
    orderNumber: 15,
    order: "Session 15",
    time: "12:15 - 12:20 PM",
    duration: "5 mins",
    title: "Debate Winner Presentation",
    shortTitle: "Debate Winner Award",
    speaker: "Debate Judges & Faculty Panel",
    category: "Competitions",
    description: "Announcement of the winning debate team, presentation of championship trophies, certificates, and cash prizes.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/iso_gear_ai.png",
    photoCaption: "Trophy Presentation to Debate Champions",
    stampText: "SESSION // 15 · DEBATE AWARDS",
    badgeColor: "bg-[#ffdb58] text-[#040032]",
  },
  {
    id: "session-16",
    orderNumber: 16,
    order: "Session 16",
    time: "12:20 - 12:45 PM",
    duration: "25 mins",
    title: "3rd Speaker Session: Engr. Adebayo Otokiti",
    shortTitle: "Engr. Adebayo Keynote (3rd Speaker)",
    speaker: "Engr. Adebayo Otokiti (Engineering Programme Manager, Calor Gas UK)",
    category: "Keynotes & Talks",
    description: "Executive Keynote: 'The Professional You Are Becoming: Why Habits and Commitments Determine Capacity Long Before Opportunity Arrives'. Refreshment snacks shared.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/otokiti.png",
    photoCaption: "Engr. Adebayo Otokiti · Engineering Programme Manager, Calor Gas UK",
    stampText: "SESSION // 16 · CALOR GAS",
    badgeColor: "bg-[#c6f552] text-[#040032]",
  },
  {
    id: "session-17",
    orderNumber: 17,
    order: "Session 17",
    time: "12:45 - 12:50 PM",
    duration: "5 mins",
    title: "Q and A: Engr. Adebayo Otokiti",
    shortTitle: "Engr. Adebayo Q&A",
    speaker: "Engr. Adebayo Otokiti & Delegates",
    category: "Keynotes & Talks",
    description: "Interactive questions on global engineering leadership, professional habits, and navigating international careers.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/otokiti.png",
    photoCaption: "Audience Q&A with Engr. Adebayo Otokiti",
    stampText: "SESSION // 17 · OTOKITI Q&A",
    badgeColor: "bg-[#c6f552] text-[#040032]",
  },
  {
    id: "session-18",
    orderNumber: 18,
    order: "Session 18",
    time: "12:50 - 12:55 PM",
    duration: "5 mins",
    title: "Award Presentation to Keynote Speakers",
    shortTitle: "Speaker Awards",
    speaker: "IESA Executives & Department Leadership",
    category: "Protocols & Ceremonies",
    description: "Conferment of honorary plaques and appreciation tokens upon our morning keynote speakers.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/kaaf_keynote.png",
    photoCaption: "Presentation of Commendation Plaques to Keynote Speakers",
    stampText: "SESSION // 18 · HONORS",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-19",
    orderNumber: 19,
    order: "Session 19",
    time: "12:55 - 1:00 PM",
    duration: "5 mins",
    title: "Networking & Intermission Break",
    shortTitle: "Networking Break",
    speaker: "All Delegates & Guests",
    category: "Protocols & Ceremonies",
    description: "Short networking interval for delegates to exchange ideas, visit partner booths, and transition to workshop tracks.",
    location: "Auditorium Concourse & Lounge",
    imageUrl: "/assets/generated/iso_ticket_badge.png",
    photoCaption: "Delegate Networking & Breakout Transition",
    stampText: "SESSION // 19 · NETWORKING",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-20",
    orderNumber: 20,
    order: "Session 20",
    time: "1:00 - 1:30 PM",
    duration: "30 mins each",
    title: "Simultaneous Hands-on Workshop Sessions",
    shortTitle: "Concurrent Workshops",
    speaker: "Oluwatobi (Robotics) · Oyindamola Esq (Tech Law) · Emmanuel (Tech and AI) · itel Energy (Energy)",
    category: "Workshops",
    description: "Concurrent breakout tracks: Robotics Workshop, Tech Law, Tech and AI, and Energy Workshop running in parallel across engineering laboratories.",
    location: "Department Engineering Labs & Breakout Rooms",
    imageUrl: "/assets/generated/facilitator.png",
    photoCaption: "Parallel Specialized Engineering & Technology Workshops",
    stampText: "SESSION // 20 · WORKSHOPS",
    badgeColor: "bg-[#3fffe8] text-[#040032]",
  },
  {
    id: "session-21",
    orderNumber: 21,
    order: "Session 21",
    time: "1:30 - 1:40 PM",
    duration: "10 mins",
    title: "Chairman Keynote Address",
    shortTitle: "Chairman Keynote",
    speaker: "Conference Chairman",
    category: "Keynotes & Talks",
    description: "Strategic keynote address charting industrial horizons, advanced manufacturing, and alumni-led capacity building.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/kaaf_keynote.png",
    photoCaption: "Conference Chairman Keynote Address",
    stampText: "SESSION // 21 · CHAIRMAN",
    badgeColor: "bg-[#c6f552] text-[#040032]",
  },
  {
    id: "session-22",
    orderNumber: 22,
    order: "Session 22",
    time: "1:40 - 1:45 PM",
    duration: "5 mins",
    title: "Sponsor Talk: Afternoon Partner Spotlight",
    shortTitle: "Afternoon Sponsor Talk",
    speaker: "Partner Delegate Representative",
    category: "Keynotes & Talks",
    description: "Afternoon corporate sponsor spotlight showcasing technical tools, graduate placement opportunities, and partner solutions.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/iso_analytics_card.png",
    photoCaption: "Corporate Partner Talk & Industrial Solutions",
    stampText: "SESSION // 22 · SPONSOR",
    badgeColor: "bg-[#c6f552] text-[#040032]",
  },
  {
    id: "session-23",
    orderNumber: 23,
    order: "Session 23",
    time: "1:45 - 2:40 PM",
    duration: "55 mins",
    title: "Research Paper Competition & Oral Defenses",
    shortTitle: "Paper Competition",
    speaker: "Student Authors & Academic Reviewers",
    category: "Paper Presentations",
    description: "Competitive oral defenses of shortlisted undergraduate research papers across optimization, supply chain, and process engineering.",
    location: "Academic Stage",
    imageUrl: "/assets/generated/iso_analytics_card.png",
    photoCaption: "Academic Research Paper Presentations & Oral Defenses",
    stampText: "SESSION // 23 · PAPERS",
    badgeColor: "bg-[#bbf2f6] text-[#040032]",
  },
  {
    id: "session-24",
    orderNumber: 24,
    order: "Session 24",
    time: "2:40 - 2:45 PM",
    duration: "5 mins",
    title: "Award Presentation to Workshop Facilitators",
    shortTitle: "Facilitator Awards",
    speaker: "IESA Executives & Faculty Panel",
    category: "Protocols & Ceremonies",
    description: "Honorary awards and commendation certificates presented to the workshop track facilitators during the paper competition interval.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/facilitator.png",
    photoCaption: "Commendation Award Presentation to Workshop Facilitators",
    stampText: "SESSION // 24 · FACILITATORS",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-25",
    orderNumber: 25,
    order: "Session 25",
    time: "2:45 - 2:50 PM",
    duration: "5 mins",
    title: "Paper Winner Presentation",
    shortTitle: "Paper Winner Award",
    speaker: "Faculty Judges & Review Committee",
    category: "Paper Presentations",
    description: "Announcement and awarding of the Best Research Paper, Research Excellence plaques, and cash prizes.",
    location: "Academic Stage",
    imageUrl: "/assets/generated/iso_analytics_card.png",
    photoCaption: "Announcement & Awarding of Research Paper Champions",
    stampText: "SESSION // 25 · PAPER AWARDS",
    badgeColor: "bg-[#bbf2f6] text-[#040032]",
  },
  {
    id: "session-26",
    orderNumber: 26,
    order: "Session 26",
    time: "2:50 - 3:05 PM",
    duration: "15 mins",
    title: "Engineering Games & Audience Trivia",
    shortTitle: "Games & Trivia",
    speaker: "Social Committee & MC",
    category: "Protocols & Ceremonies",
    description: "Interactive team trivia, quick-fire puzzle challenges, audience mini-games, and delegate prizes.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/iso_gear_ai.png",
    photoCaption: "Interactive Engineering Trivia & Social Games",
    stampText: "SESSION // 26 · GAMES",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-27",
    orderNumber: 27,
    order: "Session 27",
    time: "3:05 - 3:40 PM",
    duration: "35 mins",
    title: "Process Day Hackathon Finalist Pitches",
    shortTitle: "Hackathon Pitches",
    speaker: "Hackathon Finalist Teams & Industry Judges",
    category: "Competitions",
    description: "Live 3-minute project demos and defense pitches by the top 8 finalist teams before the judging panel.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/iso_robotic_arm.png",
    photoCaption: "Finalist Engineering Teams Pitching Live on Stage",
    stampText: "SESSION // 27 · HACKATHON",
    badgeColor: "bg-[#ffdb58] text-[#040032]",
  },
  {
    id: "session-28",
    orderNumber: 28,
    order: "Session 28",
    time: "3:40 - 3:45 PM",
    duration: "5 mins",
    title: "Peace Club Session",
    shortTitle: "Peace Club Session",
    speaker: "Peace Club Representatives",
    category: "Protocols & Ceremonies",
    description: "Special presentation emphasizing collaborative harmony, peaceful campus ecosystems, and shared leadership values.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/logo.png",
    photoCaption: "Peace Club Feature on Campus Harmony & Shared Leadership",
    stampText: "SESSION // 28 · PEACE CLUB",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-29",
    orderNumber: 29,
    order: "Session 29",
    time: "3:45 - 3:50 PM",
    duration: "5 mins",
    title: "Hackathon Winner Presentation & Grand Awards",
    shortTitle: "Hackathon Winner Award",
    speaker: "Hackathon Judges & Sponsor Representatives",
    category: "Competitions",
    description: "Announcement of the grand champion, runners-up, cash prize presentations, and investor incubation awards.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/iso_robotic_arm.png",
    photoCaption: "Coronation of IEPOD Hackathon Grand Champions",
    stampText: "SESSION // 29 · GRAND FINALS",
    badgeColor: "bg-[#ffdb58] text-[#040032]",
  },
  {
    id: "session-30",
    orderNumber: 30,
    order: "Session 30",
    time: "3:50 - 3:55 PM",
    duration: "5 mins",
    title: "Conference Lead Vote of Thanks",
    shortTitle: "Vote of Thanks",
    speaker: "Conference Lead Convener",
    category: "Protocols & Ceremonies",
    description: "Formal vote of thanks appreciating speakers, sponsors, faculty, planning committee, and delegates.",
    location: "KAAF Main Stage",
    imageUrl: "/assets/generated/logo.png",
    photoCaption: "Conference Convener Vote of Thanks & Appreciation",
    stampText: "SESSION // 30 · THANKS",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-31",
    orderNumber: 31,
    order: "Session 31",
    time: "3:55 - 3:57 PM",
    duration: "2 mins",
    title: "Closing Prayer",
    shortTitle: "Closing Prayer",
    speaker: "Appointed Delegate",
    category: "Protocols & Ceremonies",
    description: "Closing prayer giving thanks for successful conference deliberations and safe travels.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/kaaf_keynote.png",
    photoCaption: "Closing Benediction & Prayer for Delegates",
    stampText: "SESSION // 31 · PRAYER",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
  {
    id: "session-32",
    orderNumber: 32,
    order: "Session 32",
    time: "3:57 - 4:00 PM",
    duration: "3 mins",
    title: "Closing and Attendees Departure",
    shortTitle: "Closing & Departure",
    speaker: "IESA Executive Council",
    category: "Protocols & Ceremonies",
    description: "Official adjournment, departure music, networking exchanges, and appreciation of all event sponsors.",
    location: "KAAF Main Auditorium",
    imageUrl: "/assets/generated/logo.png",
    photoCaption: "Official Adjournment & Sponsor Appreciation",
    stampText: "SESSION // 32 · CONCLUSION",
    badgeColor: "bg-[#ece7d8] text-[#040032]",
  },
];
